apiVersion: batch/v1
kind: CronJob
metadata:
  name: hello
spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      activeDeadlineSeconds: 10
      template:
        spec:
          containers:
            - command:
              - sleep
              - "5"
              image: busybox
              name: hello
          restartPolicy: Never
